# Generated by Django 4.1 on 2022-09-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countfin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="create_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="spending",
            name="create_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
