# Generated by Django 4.1 on 2022-09-05 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countfin", "0002_alter_income_create_date_alter_spending_create_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="create_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="spending",
            name="create_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
